export const events = [
    {
        image: '/images/event1.png',
        title: 'React Universe Conference',
        slug: 'react-universe-conference',
        location: 'San Francisco, CA',
        date: 'Oct 15, 2025',
        time: '09:00 AM',
    },
    {
        image: '/images/event2.png',
        title: 'AI for Developers Summit',
        slug: 'ai-developers-summit',
        location: 'New York, NY',
        date: 'Nov 20, 2025',
        time: '10:00 AM',
    },
    {
        image: '/images/event3.png',
        title: 'Global Hackathon 2025',
        slug: 'global-hackathon-2025',
        location: 'Online',
        date: 'Dec 05, 2025',
        time: '08:00 PM',
    },
    {
        image: '/images/event4.png',
        title: 'Next.js Conf',
        slug: 'nextjs-conf',
        location: 'London, UK',
        date: 'Jan 12, 2026',
        time: '02:00 PM',
    },
    {
        image: '/images/event5.png',
        title: 'Tech Startup Mixer',
        slug: 'tech-startup-mixer',
        location: 'Austin, TX',
        date: 'Feb 14, 2026',
        time: '06:30 PM',
    },
    {
        image: '/images/event6.png',
        title: 'Open Source Contributors Meetup',
        slug: 'open-source-meetup',
        location: 'Berlin, Germany',
        date: 'Mar 10, 2026',
        time: '05:00 PM',
    },
];
