export const events = [
    {
        title: "TechConf 2025",
        image: "/images/event1.png",
        slug: "techconf-2025",
        location: "San Francisco, CA",
        date: "Dec 15, 2025",
        time: "09:00 AM",
    },
    {
        title: "Global Hackathon",
        image: "/images/event2.png",
        slug: "global-hackathon",
        location: "Online",
        date: "Dec 20, 2025",
        time: "10:00 AM",
    },
    {
        title: "AI Summit",
        image: "/images/event3.png",
        slug: "ai-summit",
        location: "New York, NY",
        date: "Jan 10, 2026",
        time: "08:30 AM",
    },
    {
        title: "Web Dev Meetup",
        image: "/images/event4.png",
        slug: "web-dev-meetup",
        location: "London, UK",
        date: "Jan 15, 2026",
        time: "06:00 PM",
    },
    {
        title: "Cyber Security Workshop",
        image: "/images/event5.png",
        slug: "cyber-security-workshop",
        location: "Berlin, Germany",
        date: "Jan 22, 2026",
        time: "02:00 PM",
    },
    {
        title: "Startup Pitch Night",
        image: "/images/event6.png",
        slug: "startup-pitch-night",
        location: "Austin, TX",
        date: "Feb 05, 2026",
        time: "05:00 PM",
    },
];
